In [1]:
import numpy as np

In [2]:
a=np.array([2,4,6])
print(a)

[2 4 6]


In [4]:
a=np.array([(1,3,5),(2,4,6)])
print(a)

[[1 3 5]
 [2 4 6]]


In [14]:
#dimention
n=np.array([[(1,2,3),(2,3,4),(8,7,6),(9,0,1)]])
print(n.ndim)

3


In [12]:
#to calculate/fine the byte size

print(n.itemsize)


4


In [13]:
# to know the data type

print(n.dtype)

int32


In [18]:
#to get the size of an array  

print(n.size)
print(a.size)

n.nbytes

12
6


48

In [19]:
#to get the shape of an array

r=np.array([(1,2,3,4,5,6,7),(8,9,10,11,12,13,14)])
print(r.shape)
print(r)

(2, 7)
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
#to reshapean array
#it is two dimensional array with 2 rows and 4 columns

ar=np.array([(1,2,3,4),(3,4,5,6)])
ar=ar.reshape(4,2)
print(ar)

[[1 2]
 [3 4]
 [3 4]
 [5 6]]


In [23]:
#slicing

ar1=np.array([(1,2,3,4),(3,4,5,6)])
print(ar1)
print(ar1[0,2])
print(ar1[1,0])
print(ar1[1,3])

[[1 2 3 4]
 [3 4 5 6]]
3
3
6


In [32]:
ar2=np.array([(1,2,3,4),(3,4,5,6),(5,6,7,8)])

print(ar2[0,3])
print(ar2[1,3])


4
6


In [28]:
#linespace
ls=np.linspace(1,3,5)
print(ls)

[1.  1.5 2.  2.5 3. ]


In [33]:
#find maximum(large element) from the array

m1=np.array([1,2,3])
print(m1.max())

#find maximum

print(m1.min())

#to get the sum of the array

print(m1.sum())


3
1
6


In [7]:
# axis=0,so we get the sum of each column

ar3=np.array([(1,2,3,4),(3,4,5,6)])
print(ar3)
print(ar3.sum(axis=1))

#axis=1,so we get the sum of each row

print(ar3.sum(axis=1))

[[1 2 3 4]
 [3 4 5 6]]
[10 18]
[10 18]
